steps:
  - name: 'europe-west3-docker.pkg.dev/pocagrochocinski/docker-repo/openjdk-user:latest'
    args:
      - '-c'
      - |
        echo "copy project"
        cp -r . /home/jenkins/wildfly/
        cd /home/jenkins/wildfly/
        echo "current directory: $(pwd)"
        echo "build and test"
        mvn clean install -B -Puse-gcp-artifact-registry -DallTests -Drelease=true -ntp
        mvn deploy -B -Puse-gcp-artifact-registry -DskipTests -Drelease=true -ntp
    entrypoint: bash
timeout: 21600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8